CREATE TABLE TB_EMPLOYEE (
	EMP_NO	VARCHAR2(9)		NOT NULL,
	EMP_PASSWORD	VARCHAR2(150)		NOT NULL,
	EMP_NM	VARCHAR2(30)		NOT NULL,
	EMP_EMAIL	VARCHAR2(100)		NOT NULL,
	EMP_TELNO	VARCHAR2(13)		NOT NULL,
	EMP_BRTHDY	VARCHAR2(8)		NOT NULL,
	EMP_ADDR	VARCHAR2(150)		NOT NULL,
	EMP_DTL_ADDR	VARCHAR2(150)		NOT NULL,
	EMP_ZIP	VARCHAR2(5)		NOT NULL,
	EMP_ENCPN	DATE		NOT NULL,
	EMP_RTCPN	DATE		NULL,
	EMP_SIGN_IMG_PATH	VARCHAR2(200)		NULL,
	DEPT_CODE	VARCHAR2(20)		NOT NULL,
	EMP_REG_DATE	DATE		NOT NULL,
	FIRST_LOGIN	Char(2)	DEFAULT 'Y'	NOT NULL,
	ENABLED	CHAR(1) DEFAULT '1' NULL
);

COMMENT ON COLUMN TB_EMPLOYEE.EMP_NO IS '23099001';

COMMENT ON COLUMN TB_EMPLOYEE.EMP_TELNO IS '-포함';

COMMENT ON COLUMN TB_EMPLOYEE.EMP_BRTHDY IS '19980813';

COMMENT ON COLUMN TB_EMPLOYEE.EMP_SIGN_IMG_PATH IS '/img/a001.jpg';

CREATE TABLE TB_NOTICE_BOARD (
	NTBD_CODE	VARCHAR2(50)		NOT NULL,
	WRITER_EMP_NO	VARCHAR2(9)		NOT NULL,
	NTBD_REG_DATE	DATE		NOT NULL,
	UPDATER_EMP_NO	VARCHAR2(30)		NULL,
	NTBD_UPD_DATE	DATE		NULL,
	NTBD_SUBJECT	VARCHAR2(500)		NOT NULL,
	NTBD_CONTENT	CLOB		NOT NULL,
	NTBD_HIT	NUMBER	DEFAULT 0	NOT NULL,
	COM_FILE_CODE	VARCHAR2(30)		NOT NULL
);

CREATE TABLE TB_HOS_SCHEDULE (
	HOS_SCH_NO	NUMBER		NOT NULL,
	HOS_SCH_START	VARCHAR2(10)		NOT NULL,
	HOS_SCH_START_TIME	VARCHAR2(4)		NOT NULL,
	HOS_SCH_END_DATE	VARCHAR2(10)		NOT NULL,
	HOS_SCH_END_DATE_TIME	VARCHAR2(4)		NOT NULL,
	HOS_SCH_SUBJECT	VARCHAR2(255)		NULL,
	HOS_SCH_URL	VARCHAR2(150)		NULL,
	HOS_SCH_BGCOLOR	VARCHAR2(100)	DEFAULT '샵ffffff'	NOT NULL,
	HOS_SCH_TEXTCOLOR	VARCHAR2(100)	DEFAULT '샵000000'	NOT NULL
);

COMMENT ON COLUMN TB_HOS_SCHEDULE.HOS_SCH_START IS '20230901';

COMMENT ON COLUMN TB_HOS_SCHEDULE.HOS_SCH_START_TIME IS '0900';

CREATE TABLE TB_PATIENT (
	PAT_CODE	VARCHAR2(9)		NOT NULL,
	PAT_NAME	VARCHAR2(30)		NOT NULL,
	PAT_TEL	VARCHAR2(13)		NOT NULL,
	PAT_IHIDNUM	VARCHAR2(14)		NOT NULL,
	PAT_BRTHDY	VARCHAR2(8)		NOT NULL,
	PAT_GEN_CODE	VARCHAR2(2)		NOT NULL,
	PAT_ADDR	VARCHAR2(150)		NOT NULL,
	PAT_DTL_ADDR	VARCHAR2(150)		NOT NULL,
	PAT_ZIP	VARCHAR2(5)		NOT NULL,
	PAT_FIRST_DATE	DATE		NOT NULL,
	PAT_LAST_DATE	DATE		NOT NULL,
	PAT_FRGNR_YN	VARCHAR2(2)	DEFAULT 'N'	NOT NULL,
	PAT_NATION_CODE	VARCHAR2(4)	DEFAULT 'KR'	NOT NULL,
	PAT_HSPTLZ_STATUS	VARCHAR2(2)	DEFAULT '1'	NOT NULL
);

COMMENT ON COLUMN TB_PATIENT.PAT_CODE IS '23080009 (연월 숫자 5자리)';

COMMENT ON COLUMN TB_PATIENT.PAT_TEL IS '- 포함';

COMMENT ON COLUMN TB_PATIENT.PAT_IHIDNUM IS '- 포함';

COMMENT ON COLUMN TB_PATIENT.PAT_BRTHDY IS '19941226';

COMMENT ON COLUMN TB_PATIENT.PAT_GEN_CODE IS '공통코드 M : 남성,  F : 여성';

COMMENT ON COLUMN TB_PATIENT.PAT_FRGNR_YN IS '공통코드 Y : 여,  N : 부';

COMMENT ON COLUMN TB_PATIENT.PAT_NATION_CODE IS '공통코드 KR : 한국,  JP : 일본 ...';

COMMENT ON COLUMN TB_PATIENT.PAT_HSPTLZ_STATUS IS '공통코드 1 :  default 2 :  입원결정 3 : 수속완료 4:  입원완료';

CREATE TABLE TB_CLINIC (
	TREAT_NO	VARCHAR2(9)		NOT NULL,
	RCEPT_NO	VARCHAR2(9)		NOT NULL,
	CLNIC_STTUS_CODE	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN TB_CLINIC.TREAT_NO IS '23083001';

COMMENT ON COLUMN TB_CLINIC.CLNIC_STTUS_CODE IS '공통코드 STAT';

CREATE TABLE TB_CHART_DETAIL (
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	DISS_CODE_NO	VARCHAR2(50)		NOT NULL,
	TREAT_NO	VARCHAR2(9)		NOT NULL,
	DETAIL_REG_DATE	DATE		NOT NULL,
	P_DETAIL_NO	VARCHAR2(9)		NOT NULL,
	DETAIL_MEMO	CLOB		NOT NULL
);

COMMENT ON COLUMN TB_CHART_DETAIL.TREAT_NO IS '23083001';

CREATE TABLE TB_SMS (
	SMS_NM	NUMBER		NOT NULL,
	SMS_SJ	VARCHAR2(50)		NOT NULL,
	SMS_CN	CLOB		NOT NULL
);

CREATE TABLE TB_OPINION (
	OPINION_NO	NUMBER		NOT NULL,
	REQ_OPINION_NO	VARCHAR2(5)		NOT NULL,
	OPINION_DOC_NM	VARCHAR2(12)		NOT NULL,
	OPINION_SIGN_IMG_PATH	VARCHAR2(200)	DEFAULT '이미지'	NOT NULL,
	OPINION_ISU_DATE	DATE		NOT NULL,
	OPINION_NOTE	VARCHAR2(2000)		NOT NULL,
	OPINION_RM	VARCHAR2(300)		NULL,
	OPINION_PRPOS	VARCHAR2(300)		NOT NULL
);

CREATE TABLE TB_DIAGNOSIS (
	DIAGNOSIS_NO	NUMBER		NOT NULL,
	REQ_DIAGNOSIS_NO	VARCHAR2(5)		NOT NULL,
	DIAGNOSIS_DOC_NM	VARCHAR2(12)		NOT NULL,
	DIAGNOSIS_SIGN_IMG_PATH	VARCHAR2(200)	DEFAULT '이미지'	NOT NULL,
	DIAGNOSIS_ISU_DATE	DATE		NOT NULL,
	DIAGNOSIS_DISS_CN	VARCHAR2(4000)		NOT NULL,
	DIAGNOSIS_DISS_CL_NO	VARCHAR2(50)		NOT NULL,
	DIAGNOSIS_OPINION	VARCHAR2(4000)		NOT NULL,
	DIAGNOSIS_RM	VARCHAR2(300)		NULL,
	DIAGNOSIS_PRPOS	VARCHAR2(300)		NOT NULL
);

CREATE TABLE TB_MEDI_ITEM_LIST (
	MEDI_ITEM_CODE	VARCHAR2(30)		NOT NULL,
	MEDI_ITEM_NAME	VARCHAR(1000)		NOT NULL,
	MEDI_ITEM_MAKR	VARCHAR2(300)		NOT NULL,
	MEDI_ITEM_UNIT	VARCHAR2(10)		NOT NULL,
	MEDI_ITEM_USAGE	VARCHAR2(3000)		NOT NULL,
	NARCOTIC_YN	VARCHAR2(2)		NOT NULL,
	MEDI_ITEM_PRICE	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_MEDI_ITEM_LIST.NARCOTIC_YN IS '여:Y 부:N';

CREATE TABLE TB_MEDI_ITEM_REQ_DETAIL (
	MEDI_ITEM_REQ_NO	NUMBER		NOT NULL,
	MEDI_ITEM_CODE	VARCHAR2(30)		NOT NULL,
	MEDI_ITEM_REQ_QY	NUMBER		NOT NULL,
	MEDI_ITEM_REQ_TOTAL	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_MEDI_ITEM_REQ_DETAIL.MEDI_ITEM_REQ_NO IS 'SEQ';

CREATE TABLE TB_BED (
	BED_NO	NUMBER		NOT NULL,
	BED_STAT	VARCHAR2(30)		NOT NULL,
	BED_NAME	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN TB_BED.BED_NO IS '순번';

COMMENT ON COLUMN TB_BED.BED_STAT IS '공통코드 EMPT   /  EMPT : 비어있음 FULL : 사용중';

CREATE TABLE TB_NOTIFICATION (
	NTCN_ID	NUMBER		NOT NULL,
	NTCN_RCVER_EMP_NO	VARCHAR2(9)		NOT NULL,
	NTCN_CONTENT	VARCHAR2(1000)		NOT NULL,
	NTCN_URL	VARCHAR2(1000)		NOT NULL,
	NTCN__DT	DATE		NOT NULL
);

COMMENT ON COLUMN TB_NOTIFICATION.NTCN_RCVER_EMP_NO IS '알림받는직원';

CREATE TABLE TB_RECEIPT (
	RCEPT_NO	VARCHAR2(9)		NOT NULL,
	PAT_CODE	VARCHAR2(9)		NOT NULL,
	RCEPT_PATH_CODE	VARCHAR2(2)		NOT NULL,
	RCEPT_FIRST_EXAM_CODE	VARCHAR2(2)		NOT NULL,
	RCEPT_DAY_CODE	VARCHAR2(2)		NOT NULL,
	RCEPT_MEMO	VARCHAR2(4000)		NOT NULL,
	SCHD_CODE	VARCHAR2(9)		NOT NULL,
	RECEPT_TIME	DATE		NOT NULL
);

COMMENT ON COLUMN TB_RECEIPT.RCEPT_PATH_CODE IS '0.일반';

COMMENT ON COLUMN TB_RECEIPT.RCEPT_FIRST_EXAM_CODE IS '공통코드 Y : 여,  N : 부';

COMMENT ON COLUMN TB_RECEIPT.RCEPT_DAY_CODE IS '0.주간 1.야간';

COMMENT ON COLUMN TB_RECEIPT.RCEPT_MEMO IS 'C.C';

COMMENT ON COLUMN TB_RECEIPT.SCHD_CODE IS '230827001';

CREATE TABLE TB_SMS_HISTORY (
	SMS_HIS_NO	VARCHAR2(9)		NOT NULL,
	SMS_NM	NUMBER		NOT NULL,
	SMS_HIS_RCVER	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN TB_SMS_HISTORY.SMS_HIS_NO IS 'SEQ';

CREATE TABLE TB_MEDI_ITEM_ORDER (
	MEDI_ITEM_ORDER_NO	VARCHAR2(9)		NOT NULL,
	MEDI_ITEM_REQ_NO	NUMBER		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL,
	MEDI_ITEM_RETURN_WHY	VARCHAR2(3000)		NULL,
	MEDI_ITEM_CONFIRM_YSNO	VARCHAR2(4)		NOT NULL,
	MEDI_ITEM_ORDER_DATE	DATE		NOT NULL
);

COMMENT ON COLUMN TB_MEDI_ITEM_ORDER.MEDI_ITEM_ORDER_NO IS '230902201,230902202';

COMMENT ON COLUMN TB_MEDI_ITEM_ORDER.EMP_NO IS '발주자';

COMMENT ON COLUMN TB_MEDI_ITEM_ORDER.MEDI_ITEM_CONFIRM_YSNO IS 'Y:발주승인 N:발주반려';

CREATE TABLE TB_USER_AUTHORITIES (
	AUTH_GRP_CODE	VARCHAR2(30)		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL
);

CREATE TABLE TB_INSPECTION (
	INSPC_CODE	VARCHAR2(10)		NOT NULL,
	INSPC_COST	NUMBER		NOT NULL,
	INSPC_CONTENT	VARCHAR2(30)		NOT NULL
);

CREATE TABLE TB_INSPECTION_LIST (
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	INSPC_CODE	VARCHAR2(10)		NOT NULL,
	INSPC_STATUS	VARCHAR2(3)		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL,
	INSPC_MEMO	CLOB		NULL
);

COMMENT ON COLUMN TB_INSPECTION_LIST.DETAIL_NO IS '23093001';

CREATE TABLE TB_ITEM_LIST (
	ITEM_CODE	VARCHAR2(30)		NOT NULL,
	ITEM_NAME	VARCHAR2(50)		NOT NULL,
	ITEM_MAKR	VARCHAR2(40)		NOT NULL,
	ITEM_USAGE	VARCHAR2(300)		NOT NULL,
	ITEM_PRICE	NUMBER		NOT NULL
);

CREATE TABLE TB_ITEM_REQ_DETAIL (
	ITEM_REQ_NO	NUMBER		NOT NULL,
	ITEM_CODE	VARCHAR2(30)		NOT NULL,
	ITEM_REQ_QY	NUMBER		NOT NULL,
	ITEM_REQ_TOTAL	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_ITEM_REQ_DETAIL.ITEM_REQ_NO IS 'SEQ';

CREATE TABLE TB_MEDI_ITEM_REQUEST (
	MEDI_ITEM_REQ_NO	NUMBER		NOT NULL,
	MEDI_ITEM_REQ_DE	DATE		NOT NULL,
	MEDI_ITEM_REQ_ST	VARCHAR2(2)	DEFAULT 'N'	NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL
);

COMMENT ON COLUMN TB_MEDI_ITEM_REQUEST.MEDI_ITEM_REQ_NO IS 'SEQ';

COMMENT ON COLUMN TB_MEDI_ITEM_REQUEST.MEDI_ITEM_REQ_ST IS 'Y:발주완료 N:발주대기';

COMMENT ON COLUMN TB_MEDI_ITEM_REQUEST.EMP_NO IS '신청자';

CREATE TABLE TB_MEDI_ITEM_INVENTORY (
	MEDI_ITEM_CODE	VARCHAR2(30)		NOT NULL,
	MEDI_ITEM_INVR_QTY	NUMBER		NOT NULL,
	MEDI_ITEM_LEAST_QTY	NUMBER		NOT NULL,
	MEDI_ITEM_REG_DATE	DATE		NOT NULL
);

CREATE TABLE TB_ITEM_REQ (
	ITEM_REQ_NO	NUMBER		NOT NULL,
	ITEM_REQ_DE	DATE		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL,
	ITEM_REQ_ST	VARCHAR2(2)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN TB_ITEM_REQ.ITEM_REQ_NO IS 'SEQ';

COMMENT ON COLUMN TB_ITEM_REQ.EMP_NO IS '신청자';

COMMENT ON COLUMN TB_ITEM_REQ.ITEM_REQ_ST IS 'Y:발주완료 N:발주대기';

CREATE TABLE TB_ITEM_INVENTORY (
	ITEM_CODE	VARCHAR2(30)		NOT NULL,
	ITEM_INVR_QTY	NUMBER		NOT NULL,
	ITEM_INVR_LEAST_QTY	NUMBER		NOT NULL,
	ITEM_INVR_REG_DATE	DATE		NOT NULL
);

CREATE TABLE TB_ITEM_ORDER (
	ITEM_ORDER_NO	VARCHAR2(9)		NOT NULL,
	ITEM_REQ_NO	NUMBER		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL,
	ITEM_RETURN_WHY	VARCHAR2(3000)		NULL,
	ITEM_CONFIRM_YSNO	VARCHAR2(4)		NOT NULL,
	ITEM_ORDER_DATE	DATE		NOT NULL
);

COMMENT ON COLUMN TB_ITEM_ORDER.ITEM_ORDER_NO IS '230902101,230902102';

COMMENT ON COLUMN TB_ITEM_ORDER.EMP_NO IS '발주자';

COMMENT ON COLUMN TB_ITEM_ORDER.ITEM_CONFIRM_YSNO IS 'Y:발주승인 N:발주반려';

CREATE TABLE TB_PRESCRIPTION (
	MEDI_ITEM_CODE	VARCHAR2(30)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	PRSCRPTN_AMOUNT	NUMBER		NOT NULL,
	PRSCRPTN_COUNT	NUMBER		NOT NULL,
	PRSCRPTN_DAYS	NUMBER		NOT NULL,
	PRSCRPTN_STATUS	VARCHAR2(4)		NOT NULL
);

CREATE TABLE TB_COMMON_CODE (
	COM_CODE	VARCHAR2(4)		NOT NULL,
	COM_CODE_GRP	VARCHAR2(8)		NOT NULL,
	COM_CODE_NAME	VARCHAR2(20)		NOT NULL,
	COM_CODE_DESCP	VARCHAR2(200)		NOT NULL,
	USE_YN	CHAR(1)		NOT NULL,
	UPPER_COM_CODE	VARCHAR2(4)		NULL,
	UPPER_COM_CODE_GRP	VARCHAR2(8)		NULL
);

CREATE TABLE TB_DEPARTMENT (
	DEPT_CODE	VARCHAR2(20)		NOT NULL,
	DEPT_NM	VARCHAR2(30)		NOT NULL,
	DEPT_TELNO	VARCHAR2(13)		NOT NULL,
	DEPT_LEADER	VARCHAR2(12)		NULL
);

CREATE TABLE TB_AUTH_CODE (
	AUTH_GRP_CODE	VARCHAR2(30)		NOT NULL,
	AUTH_GRP_NAME	VARCHAR2(20)		NOT NULL,
	AUTH_GRP_DESCP	VARCHAR2(500)		NOT NULL
);

CREATE TABLE TB_RADIOLOGY (
	RADIO_NO	VARCHAR2(9)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	RADIO_REGN	VARCHAR2(30)		NOT NULL,
	RADIO_TYPE	VARCHAR2(30)		NOT NULL,
	RADIO_DATE	DATE		NOT NULL,
	RADIO_PHOTO_FLPTH	VARCHAR2(500)		NOT NULL,
	RCEPT_NO	VARCHAR2(30)		NOT NULL,
	INSPC_CODE	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN TB_RADIOLOGY.RADIO_NO IS '2309023001';

CREATE TABLE TB_DISEASE (
	DISS_CODE_NO	VARCHAR2(50)		NOT NULL,
	DISS_ENG_NAME	VARCHAR2(300)		NOT NULL,
	DISS_KOR_NAME	VARCHAR2(300)		NOT NULL
);

CREATE TABLE TB_CLINIC_SCHEDULE (
	SCHD_NO	VARCHAR2(9)		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL,
	HOS_FC_N0	VARCHAR2(8)		NOT NULL,
	SCHD_DATE	VARCHAR2(10)		NOT NULL,
	SCHD_START_TIME	VARCHAR2(4)		NOT NULL,
	SCHD_END_TIME	VARCHAR2(4)		NOT NULL
);

COMMENT ON COLUMN TB_CLINIC_SCHEDULE.SCHD_NO IS '230827001';

CREATE TABLE TB_HOSPITAL_FACILITY (
	HOS_FC_NO	VARCHAR2(8)		NOT NULL,
	HOS_FC_NAME	VARCHAR2(20)		NOT NULL,
	HOS_FC_ROOM	VARCHAR2(10)		NOT NULL
);

CREATE TABLE TB_TREATMENT (
	TRE_CODE	VARCHAR2(10)		NOT NULL,
	TRE_COSTS	NUMBER		NOT NULL,
	TRE_CONTENT	VARCHAR2(200)		NOT NULL
);

CREATE TABLE TB_PHYSIOTHERAPY (
	PHYSIO_CODE	VARCHAR2(10)		NOT NULL,
	PHYSIO_COST	NUMBER		NOT NULL,
	PHYSIO_CONTENT	VARCHAR2(2000)		NOT NULL,
	PHYSIO_DATE	DATE		NOT NULL
);

CREATE TABLE TB_TREATMENT_LIST (
	TRE_CODE	VARCHAR2(10)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	TRE_STATUS	VARCHAR2(4)		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL
);

CREATE TABLE TB_PHYSIOTHERAPY_LIST (
	PHYSIO_CODE	VARCHAR2(10)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	PHYSIO_STATUS	VARCHAR2(4)		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL
);

CREATE TABLE TB_COMMON_CODE_GROUP (
	COM_CODE_GRP	VARCHAR2(8)		NOT NULL,
	CD_GROUP_NAME	VARCHAR2(30)		NOT NULL
);

CREATE TABLE TB_BED_STATUS (
	PHYSIO_CODE	VARCHAR2(10)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	BED_NO	NUMBER		NOT NULL,
	BED_STAT_DATE	DATE		NOT NULL
);

COMMENT ON COLUMN TB_BED_STATUS.BED_NO IS '순번';

CREATE TABLE TB_ATTACH_FILE (
	FILE_CODE	VARCHAR2(3)		NOT NULL,
	FILE_NO	NUMBER		NOT NULL,
	FILE_NAME	VARCHAR2(200)		NOT NULL,
	FILE_SAVE_NAME	VARCHAR2(200)		NOT NULL,
	FILE_PHYSIC_PATH	VARCHAR2(200)		NOT NULL,
	FILE_WEB_PATH	VARCHAR2(200)		NOT NULL,
	FILE_SIZE	NUMBER		NOT NULL,
	FILE_DOWN_CNT	NUMBER		NOT NULL,
	FILE_CONT_TYPE	VARCHAR2(10)		NOT NULL,
	FILE_REG_DATE	DATE		NOT NULL,
	REG_USER_ID	VARCHAR2(30)		NOT NULL,
	FILE_UPD_DATE	DATE		NULL,
	UPD_USER_ID	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN TB_ATTACH_FILE.FILE_CODE IS '100번대, 200번대';

COMMENT ON COLUMN TB_ATTACH_FILE.FILE_NO IS 'MAXNUM+1';

CREATE TABLE TB_REQUEST_OPINION (
	REQ_OPINION_NO	VARCHAR2(9)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	REQ_OPINION_REG_DATE	DATE		NOT NULL,
	REQ_OPINION_STATUS	VARCHAR2(4)		NOT NULL,
	REQ_OPINION_PAYMENT	NUMBER		NOT NULL
);

CREATE TABLE TB_REQUEST_DIAGNOSIS (
	REQ_DIAGNOSIS_NO	VARCHAR2(9)		NOT NULL,
	DETAIL_NO	VARCHAR2(9)		NOT NULL,
	REQ_DIAGNOSIS_REG_DATE	DATE		NOT NULL,
	REQ_DIAGNOSIS_STATUS	VARCHAR2(4)		NOT NULL,
	REQ_DIAGNOSIS_PAYMENT	NUMBER		NOT NULL
);

CREATE TABLE TB_HOSPITALIZATION (
	HSPTLZ_NO	VARCHAR2(9)		NOT NULL,
	PAT_CODE	VARCHAR2(9)		NOT NULL,
	TREAT_NO	VARCHAR2(9)		NOT NULL,
	HSPTLZ_PAYMENT	NUMBER		NOT NULL,
	HSPTLZ_IN_DATE	VARCHAR2(10)		NOT NULL,
	HSPTLZ_OUT_DATE	VARCHAR2(10)		NOT NULL,
	SCK_BD_NO	NUMBER		NOT NULL,
	SCKRM_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_HOSPITALIZATION.TREAT_NO IS 'seq';

COMMENT ON COLUMN TB_HOSPITALIZATION.SCK_BD_NO IS '순번 1,2,3,4,5,6';

CREATE TABLE TB_SICKBED (
	SCK_BD_NO	NUMBER		NOT NULL,
	SCKRM_NO	NUMBER		NOT NULL,
	SCK_BD_CONDITION	VARCHAR2(8)		NOT NULL
);

COMMENT ON COLUMN TB_SICKBED.SCK_BD_NO IS '순번 1,2,3,4,5,6';

CREATE TABLE TB_SICK_ROOM (
	SCKRM_NO	NUMBER		NOT NULL,
	SCKRM_TYPE_CODE	VARCHAR2(2)		NOT NULL
);

COMMENT ON COLUMN TB_SICK_ROOM.SCKRM_NO IS '201/202/';

CREATE TABLE TB_GRP_ORDR (
	GRP_ORDR_NO	VARCHAR2(20)		NOT NULL
);

CREATE TABLE TB_MENU_ASSIGN (
	AUTH_GRP_CODE	VARCHAR2(30)		NOT NULL,
	MENU_ID	VARCHAR2(20)		NOT NULL,
	READ_YN	CHAR(1)		NOT NULL,
	WRITE_YN	CHAR(1)		NOT NULL,
	DELETE_YN	CHAR(1)		NOT NULL
);

CREATE TABLE TB_MENU (
	MENU_ID	VARCHAR2(20)		NOT NULL,
	UPPER_MENU_ID	VARCHAR2(20)		NOT NULL,
	MENU_SE	VARCHAR2(5)		NOT NULL,
	MENU_ORD	NUMBER		NOT NULL,
	MENU_NAME	VARCHAR2(100)		NOT NULL,
	MENU_DSCRP	VARCHAR2(200)		NOT NULL,
	MENU_URL	VARCHAR2(100)		NOT NULL,
	USE_YN	CHAR(1)		NOT NULL
);

CREATE TABLE TB_SICK_ROOM_TYPE (
	SCKRM_TYPE_CODE	VARCHAR2(2)		NOT NULL,
	SCKRM_TYPE_OCC	NUMBER		NOT NULL,
	SCKRM_TYPE_PRICE	NUMBER		NOT NULL
);

COMMENT ON COLUMN TB_SICK_ROOM_TYPE.SCKRM_TYPE_CODE IS 'R2 : 2인, R4 : 4인, R6 : 6인';

CREATE TABLE TB_RECEIPTION (
	RCIV_CODE	VARCHAR2(9)		NOT NULL,
	TREAT_NO	VARCHAR2(9)		NOT NULL,
	RCIV_DE	DATE		NOT NULL,
	RCIV_AT	VARCHAR2(2)	DEFAULT 'N'	NOT NULL,
	RCIV_PAYMENT	NUMBER		NOT NULL,
	EMP_NO	VARCHAR2(9)		NOT NULL
);

COMMENT ON COLUMN TB_RECEIPTION.TREAT_NO IS 'seq';

COMMENT ON COLUMN TB_RECEIPTION.RCIV_AT IS 'Y:완료 N:미완료';

ALTER TABLE TB_EMPLOYEE ADD CONSTRAINT PK_TB_EMPLOYEE PRIMARY KEY (
	EMP_NO
);

ALTER TABLE TB_NOTICE_BOARD ADD CONSTRAINT PK_TB_NOTICE_BOARD PRIMARY KEY (
	NTBD_CODE
);

ALTER TABLE TB_HOS_SCHEDULE ADD CONSTRAINT PK_TB_HOS_SCHEDULE PRIMARY KEY (
	HOS_SCH_NO
);

ALTER TABLE TB_PATIENT ADD CONSTRAINT PK_TB_PATIENT PRIMARY KEY (
	PAT_CODE
);

ALTER TABLE TB_CLINIC ADD CONSTRAINT PK_TB_CLINIC PRIMARY KEY (
	TREAT_NO
);

ALTER TABLE TB_CHART_DETAIL ADD CONSTRAINT PK_TB_CHART_DETAIL PRIMARY KEY (
	DETAIL_NO
);

ALTER TABLE TB_SMS ADD CONSTRAINT PK_TB_SMS PRIMARY KEY (
	SMS_NM
);

ALTER TABLE TB_OPINION ADD CONSTRAINT PK_TB_OPINION PRIMARY KEY (
	OPINION_NO
);

ALTER TABLE TB_DIAGNOSIS ADD CONSTRAINT PK_TB_DIAGNOSIS PRIMARY KEY (
	DIAGNOSIS_NO
);

ALTER TABLE TB_MEDI_ITEM_LIST ADD CONSTRAINT PK_TB_MEDI_ITEM_LIST PRIMARY KEY (
	MEDI_ITEM_CODE
);

ALTER TABLE TB_MEDI_ITEM_REQ_DETAIL ADD CONSTRAINT PK_TB_MEDI_ITEM_REQ_DETAIL PRIMARY KEY (
	MEDI_ITEM_REQ_NO,
	MEDI_ITEM_CODE
);

ALTER TABLE TB_BED ADD CONSTRAINT PK_TB_BED PRIMARY KEY (
	BED_NO
);

ALTER TABLE TB_NOTIFICATION ADD CONSTRAINT PK_TB_NOTIFICATION PRIMARY KEY (
	NTCN_ID
);

ALTER TABLE TB_RECEIPT ADD CONSTRAINT PK_TB_RECEIPT PRIMARY KEY (
	RCEPT_NO
);

ALTER TABLE TB_SMS_HISTORY ADD CONSTRAINT PK_TB_SMS_HISTORY PRIMARY KEY (
	SMS_HIS_NO
);

ALTER TABLE TB_MEDI_ITEM_ORDER ADD CONSTRAINT PK_TB_MEDI_ITEM_ORDER PRIMARY KEY (
	MEDI_ITEM_ORDER_NO
);

ALTER TABLE TB_USER_AUTHORITIES ADD CONSTRAINT PK_TB_USER_AUTHORITIES PRIMARY KEY (
	AUTH_GRP_CODE,
	EMP_NO
);

ALTER TABLE TB_INSPECTION ADD CONSTRAINT PK_TB_INSPECTION PRIMARY KEY (
	INSPC_CODE
);

ALTER TABLE TB_INSPECTION_LIST ADD CONSTRAINT PK_TB_INSPECTION_LIST PRIMARY KEY (
	DETAIL_NO,
	INSPC_CODE
);

ALTER TABLE TB_ITEM_LIST ADD CONSTRAINT PK_TB_ITEM_LIST PRIMARY KEY (
	ITEM_CODE
);

ALTER TABLE TB_ITEM_REQ_DETAIL ADD CONSTRAINT PK_TB_ITEM_REQ_DETAIL PRIMARY KEY (
	ITEM_REQ_NO,
	ITEM_CODE
);

ALTER TABLE TB_MEDI_ITEM_REQUEST ADD CONSTRAINT PK_TB_MEDI_ITEM_REQUEST PRIMARY KEY (
	MEDI_ITEM_REQ_NO
);

ALTER TABLE TB_MEDI_ITEM_INVENTORY ADD CONSTRAINT PK_TB_MEDI_ITEM_INVENTORY PRIMARY KEY (
	MEDI_ITEM_CODE
);

ALTER TABLE TB_ITEM_REQ ADD CONSTRAINT PK_TB_ITEM_REQ PRIMARY KEY (
	ITEM_REQ_NO
);

ALTER TABLE TB_ITEM_INVENTORY ADD CONSTRAINT PK_TB_ITEM_INVENTORY PRIMARY KEY (
	ITEM_CODE
);

ALTER TABLE TB_ITEM_ORDER ADD CONSTRAINT PK_TB_ITEM_ORDER PRIMARY KEY (
	ITEM_ORDER_NO
);

ALTER TABLE TB_PRESCRIPTION ADD CONSTRAINT PK_TB_PRESCRIPTION PRIMARY KEY (
	MEDI_ITEM_CODE,
	DETAIL_NO
);

ALTER TABLE TB_COMMON_CODE ADD CONSTRAINT PK_TB_COMMON_CODE PRIMARY KEY (
	COM_CODE,
	COM_CODE_GRP
);

ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT PK_TB_DEPARTMENT PRIMARY KEY (
	DEPT_CODE
);

ALTER TABLE TB_AUTH_CODE ADD CONSTRAINT PK_TB_AUTH_CODE PRIMARY KEY (
	AUTH_GRP_CODE
);

ALTER TABLE TB_RADIOLOGY ADD CONSTRAINT PK_TB_RADIOLOGY PRIMARY KEY (
	RADIO_NO
);

ALTER TABLE TB_DISEASE ADD CONSTRAINT PK_TB_DISEASE PRIMARY KEY (
	DISS_CODE_NO
);

ALTER TABLE TB_CLINIC_SCHEDULE ADD CONSTRAINT PK_TB_CLINIC_SCHEDULE PRIMARY KEY (
	SCHD_NO
);

ALTER TABLE TB_HOSPITAL_FACILITY ADD CONSTRAINT PK_TB_HOSPITAL_FACILITY PRIMARY KEY (
	HOS_FC_NO
);

ALTER TABLE TB_TREATMENT ADD CONSTRAINT PK_TB_TREATMENT PRIMARY KEY (
	TRE_CODE
);

ALTER TABLE TB_PHYSIOTHERAPY ADD CONSTRAINT PK_TB_PHYSIOTHERAPY PRIMARY KEY (
	PHYSIO_CODE
);

ALTER TABLE TB_TREATMENT_LIST ADD CONSTRAINT PK_TB_TREATMENT_LIST PRIMARY KEY (
	TRE_CODE,
	DETAIL_NO
);

ALTER TABLE TB_PHYSIOTHERAPY_LIST ADD CONSTRAINT PK_TB_PHYSIOTHERAPY_LIST PRIMARY KEY (
	PHYSIO_CODE,
	DETAIL_NO
);

ALTER TABLE TB_COMMON_CODE_GROUP ADD CONSTRAINT PK_TB_COMMON_CODE_GROUP PRIMARY KEY (
	COM_CODE_GRP
);

ALTER TABLE TB_BED_STATUS ADD CONSTRAINT PK_TB_BED_STATUS PRIMARY KEY (
	PHYSIO_CODE,
	DETAIL_NO,
	BED_NO
);

ALTER TABLE TB_ATTACH_FILE ADD CONSTRAINT PK_TB_ATTACH_FILE PRIMARY KEY (
	FILE_CODE,
	FILE_NO
);

ALTER TABLE TB_REQUEST_OPINION ADD CONSTRAINT PK_TB_REQUEST_OPINION PRIMARY KEY (
	REQ_OPINION_NO
);

ALTER TABLE TB_REQUEST_DIAGNOSIS ADD CONSTRAINT PK_TB_REQUEST_DIAGNOSIS PRIMARY KEY (
	REQ_DIAGNOSIS_NO
);

ALTER TABLE TB_HOSPITALIZATION ADD CONSTRAINT PK_TB_HOSPITALIZATION PRIMARY KEY (
	HSPTLZ_NO
);

ALTER TABLE TB_SICKBED ADD CONSTRAINT PK_TB_SICKBED PRIMARY KEY (
	SCK_BD_NO,
	SCKRM_NO
);

ALTER TABLE TB_SICK_ROOM ADD CONSTRAINT PK_TB_SICK_ROOM PRIMARY KEY (
	SCKRM_NO
);

ALTER TABLE TB_GRP_ORDR ADD CONSTRAINT PK_TB_GRP_ORDR PRIMARY KEY (
	GRP_ORDR_NO
);

ALTER TABLE TB_MENU_ASSIGN ADD CONSTRAINT PK_TB_MENU_ASSIGN PRIMARY KEY (
	AUTH_GRP_CODE,
	MENU_ID
);

ALTER TABLE TB_MENU ADD CONSTRAINT PK_TB_MENU PRIMARY KEY (
	MENU_ID
);

ALTER TABLE TB_SICK_ROOM_TYPE ADD CONSTRAINT PK_TB_SICK_ROOM_TYPE PRIMARY KEY (
	SCKRM_TYPE_CODE
);

ALTER TABLE TB_RECEIPTION ADD CONSTRAINT PK_TB_RECEIPTION PRIMARY KEY (
	RCIV_CODE
);

ALTER TABLE TB_MEDI_ITEM_REQ_DETAIL ADD CONSTRAINT FK_MIR_MIRD1 FOREIGN KEY (
	MEDI_ITEM_REQ_NO
)
REFERENCES TB_MEDI_ITEM_REQUEST (
	MEDI_ITEM_REQ_NO
);

ALTER TABLE TB_MEDI_ITEM_REQ_DETAIL ADD CONSTRAINT FK_MIL_MIRD_1 FOREIGN KEY (
	MEDI_ITEM_CODE
)
REFERENCES TB_MEDI_ITEM_LIST (
	MEDI_ITEM_CODE
);

ALTER TABLE TB_USER_AUTHORITIES ADD CONSTRAINT FK_ACUA_1 FOREIGN KEY (
	AUTH_GRP_CODE
)
REFERENCES TB_AUTH_CODE (
	AUTH_GRP_CODE
);

ALTER TABLE TB_USER_AUTHORITIES ADD CONSTRAINT FK_EUA_1 FOREIGN KEY (
	EMP_NO
)
REFERENCES TB_EMPLOYEE (
	EMP_NO
);

ALTER TABLE TB_INSPECTION_LIST ADD CONSTRAINT FK_CDIL_1 FOREIGN KEY (
	DETAIL_NO
)
REFERENCES TB_CHART_DETAIL (
	DETAIL_NO
);

ALTER TABLE TB_INSPECTION_LIST ADD CONSTRAINT FK_IIL_1 FOREIGN KEY (
	INSPC_CODE
)
REFERENCES TB_INSPECTION (
	INSPC_CODE
);

ALTER TABLE TB_ITEM_REQ_DETAIL ADD CONSTRAINT FK_TIR_1 FOREIGN KEY (
	ITEM_REQ_NO
)
REFERENCES TB_ITEM_REQ (
	ITEM_REQ_NO
);

ALTER TABLE TB_ITEM_REQ_DETAIL ADD CONSTRAINT FK_ILIRD_1 FOREIGN KEY (
	ITEM_CODE
)
REFERENCES TB_ITEM_LIST (
	ITEM_CODE
);

ALTER TABLE TB_MEDI_ITEM_INVENTORY ADD CONSTRAINT FK_MILMIR_1 FOREIGN KEY (
	MEDI_ITEM_CODE
)
REFERENCES TB_MEDI_ITEM_LIST (
	MEDI_ITEM_CODE
);

ALTER TABLE TB_ITEM_INVENTORY ADD CONSTRAINT FK_ILII_1 FOREIGN KEY (
	ITEM_CODE
)
REFERENCES TB_ITEM_LIST (
	ITEM_CODE
);

ALTER TABLE TB_PRESCRIPTION ADD CONSTRAINT FK_MILP_1 FOREIGN KEY (
	MEDI_ITEM_CODE
)
REFERENCES TB_MEDI_ITEM_LIST (
	MEDI_ITEM_CODE
);

ALTER TABLE TB_PRESCRIPTION ADD CONSTRAINT FK_CDP_1 FOREIGN KEY (
	DETAIL_NO
)
REFERENCES TB_CHART_DETAIL (
	DETAIL_NO
);

ALTER TABLE TB_COMMON_CODE ADD CONSTRAINT FK_CCGCC_1 FOREIGN KEY (
	COM_CODE_GRP
)
REFERENCES TB_COMMON_CODE_GROUP (
	COM_CODE_GRP
);

ALTER TABLE TB_TREATMENT_LIST ADD CONSTRAINT FK_TTL_1 FOREIGN KEY (
	TRE_CODE
)
REFERENCES TB_TREATMENT (
	TRE_CODE
);

ALTER TABLE TB_TREATMENT_LIST ADD CONSTRAINT FK_CDTL_1 FOREIGN KEY (
	DETAIL_NO
)
REFERENCES TB_CHART_DETAIL (
	DETAIL_NO
);

ALTER TABLE TB_PHYSIOTHERAPY_LIST ADD CONSTRAINT FK_PPL_1 FOREIGN KEY (
	PHYSIO_CODE
)
REFERENCES TB_PHYSIOTHERAPY (
	PHYSIO_CODE
);

ALTER TABLE TB_PHYSIOTHERAPY_LIST ADD CONSTRAINT FK_CDPL_1 FOREIGN KEY (
	DETAIL_NO
)
REFERENCES TB_CHART_DETAIL (
	DETAIL_NO
);

ALTER TABLE TB_BED_STATUS ADD CONSTRAINT FK_PLBS_1 FOREIGN KEY (
	PHYSIO_CODE,DETAIL_NO
)
REFERENCES TB_PHYSIOTHERAPY_LIST (
	PHYSIO_CODE,DETAIL_NO
);


ALTER TABLE TB_BED_STATUS ADD CONSTRAINT FK_BBS_1 FOREIGN KEY (
	BED_NO
)
REFERENCES TB_BED (
	BED_NO
);

ALTER TABLE TB_SICKBED ADD CONSTRAINT FK_SRS_1 FOREIGN KEY (
	SCKRM_NO
)
REFERENCES TB_SICK_ROOM (
	SCKRM_NO
);

ALTER TABLE TB_MENU_ASSIGN ADD CONSTRAINT FK_ACMA_1 FOREIGN KEY (
	AUTH_GRP_CODE
)
REFERENCES TB_AUTH_CODE (
	AUTH_GRP_CODE
);

ALTER TABLE TB_MENU_ASSIGN ADD CONSTRAINT FK_MMA_1 FOREIGN KEY (
	MENU_ID
)
REFERENCES TB_MENU (
	MENU_ID
);

